# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [i18n]

# Permalinks
permalink:        pretty

# Setup
title:            'Meetups'
description:      "Compte-rendus des meetups et conférences auxquels je participe"
url:              http://meetups.pixelastic.com
base_url:         meetups.pixelastic.com

author:
  name:           'Timothée Carry'
  url:            https://twitter.com/pixelastic

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/pixelastic/meetups.pixelastic.com

# Build
timezone:         "Europe/Paris"
encoding:         "utf-8"

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'O3F8QXYK6R'
  index_name: 'meetups_blog_posts'
