# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Meetups'
description:      "Compte-rendus des meetups et conférences auxquels j'assiste"
url:              http://meetups.pixelastic.com/
base_url:         meetups.pixelastic.com

author:
  name:           'Timothée Carry'
  url:            https://twitter.com/pixelastic

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/pixelastic/meetups.pixelastic.com

# Build
timezone:         "Europe/Paris"
encoding:         "utf-8"
