# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Meetups'
description:      "Compte-rendus des meetups et conférences auxquelles j'assiste"
url:              http://meetups.pixelastic.com/

author:
  name:           'Timothée Carry'
  url:            https://twitter.com/pixelastic

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/pixelastic/meetups.pixelastic.com
